name: python-syntax-checker

on: [pull_request, push]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls acto
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install codespell flake8 
      - run: codespell || true  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
